### ISSUE TITLE
Use SQLAlchemy for database calls

### ISSUE THREAD

**Issue by b3yond** [ticketfrei/ticketfrei#100]
**Is your feature request related to a problem? Please describe.**
We tend to run into database locks. Also our database calls are very complicated right now.

**Describe the solution you'd like**
Use a SQL engine which is designed to do this professionally.

**Describe alternatives you've considered**
none - a contributor just said that SQLAlchemy is cool. Let's evaluate it.

**Additional context**
This would be a perfect change for #79.

**Comment by b3yond** [comment]
I started to work on this on the sqlalchemy branch.

I encountered the following issues:

## Unique Constraint

It is unclear whether the UNIQUE ON CONFLICT IGNORE works with the way I tried to define the tables: https://github.com/ticketfrei/ticketfrei/blob/sqlalchemy/sqlalchemy.py#L116

## Import doesn't work

The import doesn't work, the program exits with the following traceback:
```
Traceback (most recent call last):
  File "/home/b3yond/git/ticketfrei/sqlalchemy.py", line 1, in <module>
    from sqlalchemy.ext.declarative import declarative_base
  File "/home/b3yond/git/ticketfrei/sqlalchemy.py", line 1, in <module>
    from sqlalchemy.ext.declarative import declarative_base
ModuleNotFoundError: No module named 'sqlalchemy.ext'; 'sqlalchemy' is not a package
```

The reason could be that SQLAlchemy seems to be only compatible with CPython and Pypy, not with Python - this doesn't make a lot of sense though.

I found this thread recommending to install flask-sqlalchemy to counter the problem; but this is neither suggested in the sqlalchemy docs nor do we use flask in our project. There is also the bottle-sqlalchemy integration library, but we also want to use sqlalchemy with the backend, so that shouldn't be necessary.
